version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql

  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql-data: